# the tripod gait pattern
frequency: 1.0

joint_pairs:
  a:
    # left front leg
    - lf_shoulder_joint
    - lf_elbow_joint
    - lf_wrist_joint
    # right middle leg
    - rm_shoulder_joint
    - rm_elbow_joint
    - rm_wrist_joint
    # left back leg
    - lb_shoulder_joint
    - lb_elbow_joint
    - lb_wrist_joint
  b:
    # right front leg
    - rf_shoulder_joint
    - rf_elbow_joint
    - rf_wrist_joint
    # left middle leg
    - lm_shoulder_joint
    - lm_elbow_joint
    - lm_wrist_joint
    # right back leg
    - rb_shoulder_joint
    - rb_elbow_joint
    - rb_wrist_joint

gait:
  - a_up
  - a_foward # b_back
  - a_down
  - b_up
  - b_forward # a_back
  - b_down

# poses
up: [0.0, 0.85, -2.1, 0.0, 0.85, -2.1, 0.0, 0.85, -2.1]

down: [0.0, 0.2, -2.1, 0.0, 0.2, -2.1, 0.0, 0.2, -2.1]

forward: [0.0, 0.85, -2.1, 0.0, 0.85, -2.1, 0.0, 0.85, -2.1]

back: [0.0, 0.2, -2.1, 0.0, 0.2, -2.1, 0.0, 0.2, -2.1]
