controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_position_controller:
    type: position_controllers/JointPositionController
    joint: joint02
    pid: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  # group_position_control:
  #   type: position_controllers/JointGroupPositionController
  #   joints: 
  #     - joint01
  #     - joint02
  #     - joint03
  #     - joint04
  #     - joint05
  #     - joint06
  #     - joint07
  #     - joint08
  #     - joint09
  #     - joint10
  #     - joint11
  #     - joint12